### ISSUE TITLE
[ZBT z8102ax: Bug] Wifi Broken - openmptcprouter-v0.63-snapshot-6.12

### ISSUE THREAD

**Issue by davidohne** [Ysurac/openmptcprouter#3958]
## Expected Behavior
Wifi Devices should be present and it should be possible to create wifi networks or connect to wifi networks.

## Current Behavior
Wifi Devices are not present on most recent firmware. Menu entry is missing. 
iw list is empty

## Possible Solution
Eventually drivers are not compiled into firmware? Many of the kmod-mt packages are not available for the current 6.12 snapshot, perhaps, this is the problem.

v0.63-snapshot-6.6 is working - wifi devices are present and connectable.

## Steps to Reproduce the Problem

Upgrade or install current 6.12 snapshot on z8102ax 128mb

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.63-snapshot-6.12 r0+2961
  - OpenMPTCProuter VPS provider: Hosthatch
  - OpenMPTCProuter platform: ZBT Z8102AX 128M
  - Country: DACH

**Comment by Ysurac** [comment]
I'm working on this.

**Comment by Ysurac** [comment]
Fixed in latest snapshot

**Comment by davidohne** [comment]
> Fixed in latest snapshot

It should be here, shouldn't it: https://snapshots.openmptcprouter.com/6.12/z8102ax_128m/targets/mediatek/filogic/

Last change is May 26th on my side and in this version the Wi-Fi driver is still missing. Am I missing something?

**Comment by Ysurac** [comment]
Working for me. What is the result of ```iwinfo``` via SSH on the router ?

**Comment by davidohne** [comment]
So this is the most recent build?
```
------------------------------------------------------------------------------
   (r0+29740-8dbbca029d)
------------------------------------------------------------------------------
-----------------------------------------------------
 PACKAGE:     openmptcprouter
 VERSION:     v0.63-snapshot
 TARGET:      z8102ax_128m
 ARCH:        aarch64_cortex-a53

 BUILD REPO:  https://github.com/ysurac/openmptcprouter
 BUILD DATE:  Mon May 26 19:31:14 UTC 2025
```

```
root@OpenMPTCProuter:~# iwinfo
root@OpenMPTCProuter:~#
```

dmesg: https://pastebin.com/RrSyaycE

**Comment by Ysurac** [comment]
Try ```iw list``` and ```iw dev```.
If you keep previous config when you update then wifi is not configured at all. This may be the problem.

**Comment by davidohne** [comment]
After upgrade I removed the /etc/config/wireless since wifi interfaces were only displayed as "Generic...".
I also performed a reset. Will flash sysupgrade again..

```
root@OpenMPTCProuter:~# iw dev
root@OpenMPTCProuter:~# iw list
root@OpenMPTCProuter:~#
```

Edit: Flashed again and did't keep the settings. no wifi devices at all.
Edit 2: I've got the 128MB version. I know it doesn't make any difference, but perhaps it helps.

**Comment by davidohne** [comment]
Solved in latest snapshot. Thank you!
