### ISSUE TITLE
Glorytun TCP - Iperf3 has zero speed in one direction

### ISSUE THREAD

**Issue by Tony763** [Ysurac/openmptcprouter#4139]
## Expected Behavior

Hello, I have a small problem with Glorytun TCP. It should run almost out of box with default configuration. TCP traffic running trough MPTCP works as expected.

## Current Behavior

My Wireguard UDP tunnel go trough it,  but when I check throughput with Iperf3 (TCP) I get zero speed in one direction. Configuration seems to be correct as I can access at least ssh and basic webpage. Other services like audobookshelf are unusable.

Iperf3 server running at my home server, PC connected trough Wireguard
`iperf3 -c 10.0.1.1`:
``` 
Accepted connection from 10.0.8.3, port 52202
[  5] local 10.0.1.1 port 5201 connected to 10.0.8.3 port 52204
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  1.50 MBytes  12.6 Mbits/sec                  
[  5]   1.00-2.00   sec  3.38 MBytes  28.3 Mbits/sec                  
[  5]   2.00-3.00   sec  3.38 MBytes  28.3 Mbits/sec                  
[  5]   3.00-4.00   sec  3.38 MBytes  28.3 Mbits/sec                  
[  5]   4.00-5.00   sec  3.38 MBytes  28.3 Mbits/sec                  
[  5]   5.00-6.00   sec  3.38 MBytes  28.3 Mbits/sec                  
[  5]   6.00-7.00   sec  3.50 MBytes  29.4 Mbits/sec                  
[  5]   7.00-8.00   sec  3.25 MBytes  27.3 Mbits/sec                  
[  5]   8.00-9.00   sec  3.25 MBytes  27.3 Mbits/sec                  
[  5]   9.00-10.00  sec  3.00 MBytes  25.2 Mbits/sec                  
[  5]  10.00-10.42  sec  1.25 MBytes  24.7 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.42  sec  32.6 MBytes  26.3 Mbits/sec                  receiver
```

And `iperf3 -c 10.0.1.1 -R`:
```
Accepted connection from 10.0.8.3, port 41072
[  5] local 10.0.1.1 port 5201 connected to 10.0.8.3 port 41080
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec    9   2.44 KBytes       
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    7   1.22 KBytes       
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    5   2.44 KBytes       
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    3   2.44 KBytes       
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    2   2.44 KBytes       
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    3   1.22 KBytes       
[  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec    3   2.44 KBytes       
[  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    2   2.44 KBytes       
[  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    2   2.44 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-8.00   sec  0.00 Bytes  0.00 bits/sec   34            sender
```

## Specifications

  - OpenMPTCProuter version: v0.64-snapshot-6.12 r0+31654-3570dee5f0
  - OpenMPTCProuter VPS version: 6.12.47-x64v3-xanmod1 0.1042-rolling-test
  - OpenMPTCProuter VPS provider: [Zoner a.s.](https://www.zonercloud.cz/)
  - OpenMPTCProuter platform: x86_64

Logs:
https://pastebin.com/jy87gj41
https://pastebin.com/4NmAtPkM

**Comment by Tony763** [comment]
Tracked down to MTU. As there is overhead in using Wireguard inside Glorytun, I had to lower MTU to 1300 for Wireguard (local and remote PC) and 1340 for Glorytun (Router and VPS). With these settings applied, tunel is stable and I can measure around 200 Mbps in both directions (link limit).
But I have problem set these permanently. If I change MTU at omrvps interface at luci, it will get reverted back to 1500 after few hours.

Edit: Found setting for MTU also in `/etc/config/openmptcprouter` so will see if it is it

**Comment by Ysurac** [comment]
Should be fixed in last snapshot: https://snapshots.openmptcprouter.com/6.12/

**Comment by Tony763** [comment]
Hi, @Ysurac, I just updated to openmptcprouter-v0.64-snapshot-6.12-r0+31654-3570dee5f0-x86-64-generic-ext4-combined-efi.img.gz / November 26, 2025.

I changed MTU in luci > network > interfaces for tun0 from 1500 to 1340 and applied. 

<img width="407" height="105" alt="Image" src="https://github.com/user-attachments/assets/37d6de84-87a5-4a4b-89c2-88325772412b" />

In console I still see 1500 when I list interfaces.

<img width="808" height="42" alt="Image" src="https://github.com/user-attachments/assets/d69224fc-79a2-4e05-9616-38c4d66898f8" />

**Comment by Ysurac** [comment]
I used the wrong setting... Fix in latest snapshot that is now building

**Comment by Tony763** [comment]
Hello @Ysurac, I updated to latest snapshot (`v0.64-snapshot-6.12-r0+31654-3570dee5f0`) and value seems to be now set correctly. Now I need to set it same on VPS side. Is it supposed to be set automatically or is there a place in config, that I can change on VPS side?

<img width="865" height="51" alt="Image" src="https://github.com/user-attachments/assets/46b81fed-a9ea-40a8-aa31-873ca38cebbb" />

<img width="421" height="140" alt="Image" src="https://github.com/user-attachments/assets/8268cf91-2af6-42d2-9269-b9b8c80884e3" />

**Comment by Ysurac** [comment]
No I didn't make something to change MTU on server side automatically. If you set them manually it's reset after some times ?
I will try to add something on API for that, but I don't think this will be made before January.

**Comment by Tony763** [comment]
I did not find any config and if I change it with `ip` command it changes back after some time.

<img width="1418" height="348" alt="Image" src="https://github.com/user-attachments/assets/9f1e0139-69e6-482f-b6bb-337afa58c91d" />

Edit: for now I forced MTU by adding `ip link set dev ${INTF} mtu 1440 2>&1 >/dev/null` into `/etc/glorytun-tcp/post.sh` at VPS.

**Comment by Tony763** [comment]
Hi @Ysurac, I see another thing. TUN ifce is constantly removed and recreated.

<img width="330" height="137" alt="Image" src="https://github.com/user-attachments/assets/678bf44d-a749-4fca-83d8-461dcfaa24e5" />

```
Jan 02 14:57:37 vps3635 OMR-Service[205052]: No answer from VPN client end, restart Glorytun-TCP
Jan 02 14:57:37 vps3635 glorytun-tcp-run[197536]: INITIALIZED gt-tun0
Jan 02 14:57:37 vps3635 glorytun-tcp-run[197536]: STARTED gt-tun0
Jan 02 14:57:37 vps3635 glorytun-tcp-run[197536]: STOPPED gt-tun0
Jan 02 14:57:37 vps3635 systemd[1]: Stopping glorytun-tcp@tun0.service - Glorytun TCP on tun0...
Jan 02 14:57:37 vps3635 systemd-networkd[445]: gt-tun0: Link DOWN
Jan 02 14:57:37 vps3635 systemd-networkd[445]: gt-tun0: Lost carrier
Jan 02 14:57:37 vps3635 networkctl[205054]: Interface "gt-tun0" not found.
Jan 02 14:57:37 vps3635 systemd[1]: glorytun-tcp@tun0.service: Deactivated successfully.
Jan 02 14:57:37 vps3635 systemd[1]: Stopped glorytun-tcp@tun0.service - Glorytun TCP on tun0.
Jan 02 14:57:37 vps3635 systemd[1]: networkd-dispatcher.service: Got notification message from PID 205054, but reception only permitted for main PID 619
Jan 02 14:57:37 vps3635 systemd[1]: networkd-dispatcher.service: Got notification message from PID 205054, but reception only permitted for main PID 619
Jan 02 14:57:37 vps3635 networkd-dispatcher[619]: ERROR:Failed to get interface "gt-tun0" status: Command '['/usr/bin/networkctl', 'status', '--no-pager', '--no-legend', '--lines=0', '--', 'gt-tun0']' r>
Jan 02 14:57:37 vps3635 systemd[1]: Starting glorytun-tcp@tun0.service - Glorytun TCP on tun0...
Jan 02 14:57:37 vps3635 networkd-dispatcher[619]: WARNING:Unknown index 1077 seen, reloading interface list
Jan 02 14:57:37 vps3635 systemd[1]: networkd-dispatcher.service: Got notification message from PID 205065, but reception only permitted for main PID 619
Jan 02 14:57:38 vps3635 systemd-networkd[445]: gt-tun0: Link UP
Jan 02 14:57:38 vps3635 systemd-networkd[445]: gt-tun0: Gained carrier
Jan 02 14:57:38 vps3635 systemd[1]: networkd-dispatcher.service: Got notification message from PID 205070, but reception only permitted for main PID 619
Jan 02 14:57:38 vps3635 systemd-networkd[445]: gt-tun0: Gained IPv6LL
Jan 02 14:57:38 vps3635 systemd[1]: Started glorytun-tcp@tun0.service - Glorytun TCP on tun0.
Jan 02 14:57:38 vps3635 systemd[1]: networkd-dispatcher.service: Got notification message from PID 205081, but reception only permitted for main PID 619
Jan 02 14:57:38 vps3635 glorytun-tcp-run[205059]: ::ffff:1xx.xxx.xx.xxx.38736: connected
Jan 02 14:57:38 vps3635 glorytun-tcp-run[205059]: couldn't set socket option `TCP_USER_TIMEOUT'
Jan 02 14:57:49 vps3635 omr-admin.py[1298]: INFO:     127.0.0.1:47843 - "GET / HTTP/1.1" 200 OK
```

**Comment by Ysurac** [comment]
There is a script on VPS, when glorytun TCP is selected as VPN, that check if router end answer o ping. If not it restart glorytun TCP.

**Comment by Tony763** [comment]
Found it on openwrt side, tun0 did not get ip from config.
<img width="1347" height="278" alt="Image" src="https://github.com/user-attachments/assets/5f1ead2e-aaab-4a2c-a674-ab9a0012d48d" />

Edit: restart fixed it, so will see if it lost settings over time.

**Comment by Tony763** [comment]
Hello @Ysurac, IP is lost after a day on openwrt side. `tun0` is marked as 18, so it was recreated multiple times.
 
<img width="1371" height="190" alt="Image" src="https://github.com/user-attachments/assets/6997f180-81c5-4125-9997-7d431a35beda" />

<img width="927" height="73" alt="Image" src="https://github.com/user-attachments/assets/bc82853c-8f66-42ed-a2b7-4f62b1f6129d" />

**Comment by Tony763** [comment]
With `v0.64-snapshot-6.18 r0+32439-5578eb69c2`, IP was lost after eight days. Will try latest release.
